"""add_signals_table

Revision ID: 1553a94511fd
Revises: 6ff7a024a903
Create Date: 2026-07-14 23:14:15.839173
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '1553a94511fd'
down_revision: Union[str, None] = '6ff7a024a903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('risk_reward', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('indicators_used', sa.Text(), nullable=True),
    sa.Column('market_trend', sa.String(length=20), nullable=True),
    sa.Column('h1_signal', sa.String(length=10), nullable=True),
    sa.Column('h4_signal', sa.String(length=10), nullable=True),
    sa.Column('d1_signal', sa.String(length=10), nullable=True),
    sa.Column('ai_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_result', sa.String(length=10), nullable=True),
    sa.Column('outcome_profit', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('outcome_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    op.create_index('ix_signals_symbol_created', 'signals', ['symbol', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_symbol_created', table_name='signals')
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###
