"""initial_tables

Revision ID: 6ff7a024a903
Revises: 
Create Date: 2026-07-14 18:14:44.670689
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '6ff7a024a903'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('impact', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_currency', 'news', ['currency'], unique=False)
    op.create_index('ix_news_published_at', 'news', ['published_at'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('pip_size', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('contract_size', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=True)
    op.create_table('ohlc',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('spread', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe', 'timestamp', name='uq_ohlc_symbol_tf_ts')
    )
    op.create_index('ix_ohlc_symbol_tf', 'ohlc', ['symbol_id', 'timeframe'], unique=False)
    op.create_index('ix_ohlc_symbol_tf_ts', 'ohlc', ['symbol_id', 'timeframe', 'timestamp'], unique=False)
    op.create_table('ticks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bid', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('ask', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('last', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticks_symbol_id_ts', 'ticks', ['symbol_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticks_symbol_id_ts', table_name='ticks')
    op.drop_table('ticks')
    op.drop_index('ix_ohlc_symbol_tf_ts', table_name='ohlc')
    op.drop_index('ix_ohlc_symbol_tf', table_name='ohlc')
    op.drop_table('ohlc')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('ix_news_published_at', table_name='news')
    op.drop_index('ix_news_currency', table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
